añadido crear usuario sin derechos root

diff --git a/apps-guadalinex-20 b/apps-guadalinex-20
--- a/apps-guadalinex-20
+++ b/apps-guadalinex-20
@@ -107,6 +107,30 @@ distribucion=$(lsb_release -cs)
 		cd ..
 		}
 		
+		function usuario {
+		echo ""
+		echo "Ingrese el nombre del nuevo usuario sin permisos root"
+		echo ""
+		read usuario
+		if [ "$usuario" == "" ] ; then
+  			echo -e "\n"
+  			echo "El nombre no puede estar vacío, ejecute el script otra vez."
+  			echo -e "\n"
+  			exit 1
+  			fi
+  		if [ "$?" != 0 ] ; then
+   			echo -e "\n"
+  			echo "Ha ocurrido un error, asegurese de que los datos ingresados son correctos."
+  			exit 1
+			fi
+		echo -e "\n"
+		sudo useradd -m -d /home/$usuario -G adm,cdrom,dip,plugdev,lpadmin,sambashare $usuario -s /bin/bash
+		echo "Ingrese una contraseña para el usuario, $usuario"
+		sudo passwd $usuario
+		echo -e "\n"
+		echo "El usuario fue creado satisfactoriamente"
+		}
+		
 # Ejecuta la función correspondiente a cada una de las opciones del script
 # ---
 
@@ -166,6 +190,7 @@ opc=$( \
     False installBlinklearning "Instalar aplicación blinklearning - Usado en libros de Oxford" \
     False installActivdre "Instalar drivers pizarras Promethean y aplicación ActivInspire" \
     False installSmartdre "Instalar drivers pizarras Smartboard-incluida SB480" \
+    False usuario "Crear usuario sin derechos admin." \
 )
 
 # Comprobamos que no se pulse el botón Cancelar
diff --git a/apps-guadalinex-20-bash b/apps-guadalinex-20-bash
--- a/apps-guadalinex-20-bash
+++ b/apps-guadalinex-20-bash
@@ -32,6 +32,8 @@ echo 	" 9. Instalar drivers pizarras Promethean y aplicación ActivInspire"
 echo	""
 echo	" 10. Instalar drivers pizarras Smartboard-incluida SB480"
 echo	""
+echo	" 11. Crear usuario sin derechos admin." 
+echo	""
 echo 	" 0. Salir"
 echo	""
 echo 	"+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
@@ -132,10 +134,34 @@ case $op in
 		cd ..;break;;
 		
 		# Instalar drivers pizarras Smartboard-incluida SB480
-[10]* )		git clone https://github.com/aosucas499/smartdre.git
+[10]* )	git clone https://github.com/aosucas499/smartdre.git
 		cd smartdre
 		chmod +x install-smartdre
 		./install-smartdre
+		cd ..;break;;
+		
+		# Crear usuario sin derechos admin
+[11]* )	echo ""
+		echo "Ingrese el nombre del nuevo usuario sin permisos root"
+		echo ""
+		read usuario
+		if [ "$usuario" == "" ] ; then
+  			echo -e "\n"
+  			echo "El nombre no puede estar vacío, ejecute el script otra vez."
+  			echo -e "\n"
+  			exit 1
+  			fi
+  		if [ "$?" != 0 ] ; then
+   			echo -e "\n"
+  			echo "Ha ocurrido un error, asegurese de que los datos ingresados son correctos."
+  			exit 1
+			fi
+		echo -e "\n"
+		sudo useradd -m -d /home/$usuario -G adm,cdrom,dip,plugdev,lpadmin,sambashare $usuario -s /bin/bash
+		echo "Ingrese una contraseña para el usuario, $usuario"
+		sudo passwd $usuario
+		echo -e "\n"
+		echo "El usuario fue creado satisfactoriamente"
 		cd ..;break;;
 		
 		
