Add files via upload

diff --git a/update-guadalinex-20 b/update-guadalinex-20
--- a/update-guadalinex-20
+++ b/update-guadalinex-20
@@ -1,32 +1,61 @@
 #!/bin/bash
+#wget --no-check-certificate --content-disposition https://github.com/aosucas499/guadalinex/raw/main/update-guadalinex-20
 clear
 
+#Menu opciones
 echo ""
-echo "Creamos un usuario con derechos de administrador distinto de root. Por ejemplo, admin."
+echo "Este script tiene que ser ejecutado con sudo update-guadalinex-20" 
 echo ""
-echo "Este script tiene que ser ejecutado con usuario root"
+echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
+echo " 1. Salir"
+echo " 2. Actualizar a Educaandos con usuario administrador distinto de root."
+echo " 3. Actualizar a Educaandos sin usuario administrador, para usar en el centro." 
+echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
 echo ""
-sleep 2
-#Crear usuario administrador
-echo "Ingrese el nombre del nuevo usuario administrador, distinto de root."
-read usuario
-if [ "$usuario" == "" ] ; then
-  echo -e "\n"
-  echo "El nombre no puede estar vacío"
-  echo -e "\n"
-  exit 1
-fi
-sudo useradd -m -d /home/$usuario -G sudo $usuario
-if [ "$?" != 0 ] ; then
-   echo -e "\n"
-  echo "Ha ocurrido un error, asegurese de que los datos ingresados son correctos."
-  exit 1
-fi
-echo -e "\n"
-echo "Ingrese una contraseña para $usuario"
-sudo passwd $usuario
-echo -e "\n"
-echo "El usuario fue creado satisfactoriamente"
+echo ""
+while true; do
+read -p "Seleccione una opción, 1, 2 o 3: " op
+case $op in
+
+[1]* ) exit;;
+[2]* )
+	clear
+	# Introducción al script crear usuario admin
+	echo ""
+	echo""
+	echo "Crearemos un usuario con derechos de administrador distinto de root. Por ejemplo, admin."
+	echo ""
+	echo "Este script tiene que ser ejecutado con usuario root"
+	echo ""
+	echo ""
+	sleep 2
+
+	#Crear usuario administrador
+	echo "Ingrese el nombre del nuevo usuario administrador, distinto de root."
+	read usuario
+	if [ "$usuario" == "" ] ; then
+  	echo -e "\n"
+  	echo "El nombre no puede estar vacío, ejecute el script otra vez."
+  	echo -e "\n"
+  	exit 1
+	fi
+	sudo useradd -m -d /home/$usuario -G sudo $usuario
+	if [ "$?" != 0 ] ; then
+   	echo -e "\n"
+  	echo "Ha ocurrido un error, asegurese de que los datos ingresados son correctos."
+  	exit 1
+	fi
+	echo -e "\n"
+	echo "Ingrese una contraseña para el usuario con derechos de administrador, $usuario"
+	sudo passwd $usuario
+	echo -e "\n"
+	echo "El usuario fue creado satisfactoriamente"; break;;
+
+[3]* ) echo "Selecionada opción 2"; break;;
+esac
+done
+
 #Descargamos e instalamos los repositorios de Educaandos
 #deb [arch=amd64] http://centros.edu.guadalinex.org/Edu/focal educaandos main
 wget http://centros.edu.guadalinex.org/Edu/focal/pool/main/c/cga-sourceslist-config/cga-sourceslist-config_0.3-2_all.deb
+sudo dpkg -i apt upgrade -y
